create table if not exists public.invitation_recipients (
  id bigint generated by default as identity primary key,
  first_name text not null,
  email text not null unique,
  association_name text null,
  invitation_type text not null check (invitation_type in ('csuites', 'associates')),
  sent_at timestamptz null,
  last_error text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at_invitation_recipients()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_invitation_recipients_updated_at on public.invitation_recipients;

create trigger trg_invitation_recipients_updated_at
before update on public.invitation_recipients
for each row
execute function public.set_updated_at_invitation_recipients();
